### ISSUE TITLE
segfault due to missing files

### ISSUE THREAD

**Issue by Strugglemeat** [ProgKea/platformer#1]
WARNING: FILEIO: [data/sprites/herochar sprites(new)/herochar_idle_anim_strip_4.png] Failed to open file
WARNING: FILEIO: [data/sprites/herochar sprites(new)/herochar_run_anim_strip_6.png] Failed to open file
WARNING: FILEIO: [data/sprites/herochar sprites(new)/herochar_jump_up_anim_strip_3.png] Failed to open file
WARNING: FILEIO: [data/sprites/herochar sprites(new)/herochar_jump_double_anim_strip_3.png] Failed to open file
WARNING: FILEIO: [data/sprites/herochar sprites(new)/herochar_jump_down_anim_strip_3.png] Failed to open file
WARNING: FILEIO: [data/sprites/tiles/tileset_32x32(new).png] Failed to open file
zsh: segmentation fault (core dumped)  ./wallhugger

**Comment by ProgKea** [comment]
Hey, thank you for trying to check out my game. I didn't really know how to program back then and I didn't even include the assets. I tried to download the assets, but the assets I used are not free anymore: https://o-lobster.itch.io/platformmetroidvania-pixel-art-asset-pack

Maybe I will write a similar game with the knowledge I have today and don't forget to include the assets haha.
